# Default values for portal-objetos-aprendizaje.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

## Project dependencies (it can be configured to deploy with the chart or connect to external services) ##

# PostgreSQL is a core dependency of the project, serving as the primary database for storing all structured information. It provides a reliable and scalable solution for managing data, ensuring consistency and performance. The dependency can be deployed alongside the project chart or configured to connect to an external PostgreSQL instance, offering flexibility to adapt to different environments and infrastructure setups.
postgresql:
  # Determine if this resource should be created by helm app
  enabled: true
  # It is possible to use same secret for all postgresql values or use different secrets for each value
  postgresqlUserSecret: "poa-postgresql-secret"
  postgresqlPasswordSecret: "poa-postgresql-secret"
  postgresqlDatabase: "portal-objetos-aprendizaje"
  postgresqlTablePrefix: "qvkei_"
  # If postgresql deployment is enabled
  existingPVClaim: "pvc-portal-objetos-aprendizaje-postgresql"
  # Customize service docker image used (image, tag, pullPolicy, pullSecrets)
  image:
    tag: "pg17"
    repository: pgvector/pgvector
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # If postgresql deployment is not enabled (use external database), the external database requires pg_vector extension
  postgresqlHostSecret: "poa-postgresql-secret"
  postgresqlPort: 5432

# Kafka is a key dependency of the project, acting as the central messaging system for managing platform output events. It enables reliable, high-throughput, and scalable event streaming, ensuring seamless communication between components and efficient processing of event data. The dependency can be deployed alongside the project chart or configured to connect to an external Kafka instance, providing flexibility to integrate with various environments and infrastructure setups.
kafka:
  # Determine if this resource should be created by helm app
  enabled: true
  # If kafka deployment is enabled
  # Customize service docker image used (image, tag, pullPolicy, pullSecrets)
  image:
    tag: "3.7"
    repository: bitnami/kafka
    pullPolicy: IfNotPresent
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  # Zookeeper is a supporting dependency of the project, required only when the Kafka chart deployment is enabled. It acts as a coordination service for Kafka, managing broker metadata, leader election, and maintaining the overall cluster state. Zookeeper ensures the reliability and consistency of the Kafka deployment, but it is not needed when connecting to an external Kafka instance, providing flexibility based on the chosen deployment strategy.
  zookeeper:
    # Customize service docker image used (image, tag, pullPolicy, pullSecrets)
    image:
      tag: "3.9"
      repository: bitnami/zookeeper
      pullPolicy: IfNotPresent
      pullSecrets: []
    resources: {}
      # If you do want to specify resources (this will apply all the deployments), uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
  # If kafka deployment is not enabled
  kafkaHost: "override-kafka.host"
  kafkaPort: 9092


## Project deployment configurations (required to be deployed with chart) ##

# Admin is the main interface for managing the platform, providing a user-friendly dashboard for content creation, curation, and administration. It serves as the primary tool for managing the platform's content and user interactions, ensuring a seamless and efficient experience for all users.
admin:
  # PublicURL is used for url generation and ingress if enabled togheter to parametrization of service
  publicUrl: "https://portal-objetos-aprendizaje-admin.k8s.local"
  # Used for laravel configuration (seed for tokens, session, etc.)
  # needs to be a valid key generated with "php artisan key:generate" (ex. base64:X/tI11778LT12XntodYdmSrpbtgh9WNzjmlfxBzu1bw=)
  appKeySecret: "poa-admin-appkey-secret"
  # SAML2 Service Provider cert secret, needs to be in PEM format, recommended to generate a new one with openssl
  saml2SpCertSecret: "poa-admin-saml2-sp-cert-secret"
  # Admin web api key, used for communication between admin and web services
  adminWebApiKeySecret: "poa-admin-web-api-key-secret"
  # Session lifetime in minutes
  sessionLifetime: "120"
  # Route uri for default fallback image
  defaultImageRoute: /data/images/default_images/no_image_attached.svg
  # Interface app color configuration
  colorPrimary: "#2C4C7E"
  colorSecondary: "#507AB9"
  # General error message
  generalErrorMessage: "Ha ocurrido un error"
  # Password Reset Token expiration in minutes
  pwresTokenExpirationMin: "60"
  # Header for fmnt client cert (needs to be in PEM format)
  fmntCertHeader: "X-Forwarded-Tls-Client-Cert"
  # Persistent volume claims names for service
  existingPVClaimPublic: "pvc-portal-objetos-aprendizaje-admin-public"
  existingPVClaimProtected: "pvc-portal-objetos-aprendizaje-admin-protected"
  # Customize service docker image used (image, tag, pullPolicy, pullSecrets)
  image:
    tag: "latest"
    repository: ghcr.io/objetos-aprendizaje/portal-administracion
    pullPolicy: Always
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

# The web interface is the main access point to the platform’s content, providing an intuitive and user-friendly experience for browsing, searching, and interacting with resources. It acts as the primary tool for users to explore and consume content efficiently and seamlessly.
web:
  # PublicURL is used for url generation and ingress if enabled togheter to parametrization of service
  publicUrl: "https://portal-objetos-aprendizaje-web.k8s.local"
  # Used for laravel configuration (seed for tokens, session, etc.)
  # needs to be a valid key generated with "php artisan key:generate" (ex. base64:X/tI11778LT12XntodYdmSrpbtgh9WNzjmlfxBzu1bw=)
  appKeySecret: "poa-web-appkey-secret"
  # Session lifetime in minutes
  sessionLifetime: "120"
  # Route uri for default fallback image
  defaultImageRoute: /images/no_image_attached.svg
  # Interface app color configuration
  colorPrimary: "#2C4C7E"
  colorSecondary: "#507AB9"
  # Secret salt key for authorization hash check
  fmntSsoKeyCheckHashSaltSecret: "poa-sso-fmnt-hash-salt-secret"
  # Domain used for fmnt login page (used for client cert validation)
  fmntLoginUrl: "https://portal-objetos-aprendizaje-cert.k8s.local"
  # Header for fmnt client cert (needs to be in PEM format)
  fmntCertHeader: "X-Forwarded-Tls-Client-Cert"
  # Customize service docker image used (image, tag, pullPolicy, pullSecrets)
  image:
    tag: "latest"
    repository: ghcr.io/objetos-aprendizaje/portal-web
    pullPolicy: Always
    pullSecrets: []
  resources: {}
    # If you do want to specify resources (this will apply all the deployments), uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

# Create Ingress resources from chart installation. This is optional, it's also possible to disable and use your own Ingress controller.
ingress:
  # Determine if this resource should be created by helm app
  enabled: true
  className: "" # ex: "traefik"
  pathType: ImplementationSpecific
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

  # Setup https certificate secrets for the different services hosts (defined in publicUrl of admin and web services)
  admin:
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - portal-objetos-aprendizaje-admin.k8s.local
  web:
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - portal-objetos-aprendizaje-web.k8s.local



## ----- ##
## Other optional configurations and advanced features. Not required for app usage ##
## ----- ##

# Generic service configuration for all services deployed by this chart
service:
  type: ClusterIP
  port: 80

replicaCount: 1
# NOTE: HorizontalPodAutoscaler is not supported unless php session is stored in a shared storage
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployments (all) definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployments (all) definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# Node labels for pod assignment
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
