apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal-objetos-aprendizaje.fullname" . }}-web
  labels:
    {{- include "portal-objetos-aprendizaje.labels" . | nindent 4 }}
    {{- include "portal-objetos-aprendizaje-web.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portal-objetos-aprendizaje-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portal-objetos-aprendizaje.labels" . | nindent 8 }}
        {{- include "portal-objetos-aprendizaje-web.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.web.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "portal-objetos-aprendizaje.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: APP_ENV
              value: production
            - name: APP_DEBUG
              value: "true"

            - name: APP_NAME
              value: "WEB_PORTAL"
            - name: TIMEZONE_DISPLAY
              value: "Europe/Madrid"
            - name: TIMEZONE
              value: "UTC"
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.web.appKeySecret }}"
                  key: app_key
            - name: SESSION_LIFETIME
              value: "{{ .Values.web.sessionLifetime }}"
            - name: COLOR_PRIMARY
              value: "{{ .Values.web.colorPrimary }}"
            - name: COLOR_SECONDARY
              value: "{{ .Values.web.colorSecondary }}"
            - name: BACKEND_URL
              value: "{{ .Values.admin.publicUrl }}"
            - name: KEY_CHECK_CERTIFICATE_ACCESS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.web.fmntSsoKeyCheckHashSaltSecret }}"
                  key: salt_secret
            - name: URL_LOGIN_CERT
              value: "{{ .Values.web.fmntLoginUrl }}"
            - name: FMNT_CERT_HEADER
              value: "{{ .Values.web.fmntCertHeader }}"
            - name: API_KEY_BACKEND_WEBHOOKS
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.admin.adminWebApiKeySecret }}"
                  key: api_key
            - name: DEFAULT_IMAGE_ROUTE
              value: "{{ .Values.web.defaultImageRoute }}"

            # FIXME: Subject to remove after the implementation of environment selection at app options
            - name: REDSYS_ACTION_URL
              value: "https://sis-t.redsys.es:25443/sis/realizarPago"

            - name: APP_URL
              value: "{{ .Values.web.publicUrl }}"

            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              {{- if .Values.postgresql.enabled }}
              value: {{ include "portal-objetos-aprendizaje.fullname" . }}-postgresql-service
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.postgresqlHostSecret }}"
                  key: host
              {{- end }}
            - name: DB_PORT
              {{- if .Values.postgresql.enabled }}
              value: "5432"
              {{- else }}
              value: "{{ .Values.postgresql.postgresqlPort }}"
              {{- end }}
            - name: DB_DATABASE
              value: "{{ .Values.postgresql.postgresqlDatabase }}"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.postgresqlUserSecret }}"
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.postgresql.postgresqlPasswordSecret }}"
                  key: password
            - name: DB_PREFIX
              value: "{{ .Values.postgresql.postgresqlTablePrefix }}"

            # Variables without option to configure
            - name: GOOGLE_REDIRECT_URL
              value: "${APP_URL}/auth/callback/google"
            - name: FACEBOOK_REDIRECT_URL
              value: "${APP_URL}/auth/callback/facebook"
            - name: TWITTER_REDIRECT_URL
              value: "${APP_URL}/auth/callback/twitter"
            - name: LINKEDIN_REDIRECT_URL
              value: "${APP_URL}/auth/callback/linkedin-openid"
            - name: DS_MERCHANT_MERCHANTURL
              value: "${APP_URL}/webhook/process_payment_redsys"

          {{/*
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          */}}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
