apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-portal-objetos-aprendizaje-postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: portal-objetos-aprendizaje-postgresql
  hostPath:
    # TODO: Change this path to a more suitable one
    path: /tmp/postgresql-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-portal-objetos-aprendizaje-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: portal-objetos-aprendizaje-postgresql
  resources:
    requests:
      storage: 10Gi
